i've tested on an vanilla debian docker.io and get the following error
  ERROR: The Compose file './docker-compose.yaml' is invalid because:
  services.wavelog-db.environment.MARIADB_RANDOM_ROOT_PASSWORD contains true, which is an invalid type, it should be a string, number, or a null

found the solution and explanation on stackoverflow
  * https://stackoverflow.com/questions/66853440/docker-compose-error-invalid-type-it-should-be-a-string